### ISSUE TITLE
Different colors than in screenshots

### ISSUE THREAD

**Issue by shelldandy** [mhartington/oceanic-next#37]
Hi @mhartington i was wondering if you ran into similar issues, im using iterm 2 with tmux and also installed the oceanic next color scheme on my terminal so by default it looks like this:

![captura de pantalla 2016-11-27 a la s 11 39 36](https://cloud.githubusercontent.com/assets/7088511/20650535/6930344a-b496-11e6-9ebf-3829a18feff8.png)

However after setting everything in my `.vimrc` file for some reason I get a dull grey background instead of the nice blue one:

![captura de pantalla 2016-11-27 a la s 11 39 53](https://cloud.githubusercontent.com/assets/7088511/20650539/88950a4a-b496-11e6-9407-9b768fdeb0d0.png)

Am I missing something? I'm using Vim 7.4.898 for reference. Thanks

**Comment by mhartington** [comment]
Can provide  a minimal vimrc file to test against?

**Comment by shelldandy** [comment]
How minimal?

I copied what's on the readme:

```
 " Theme
syntax enable
" for vim 7
set t_Co=256

" for vim 8
if (has("termguicolors"))
 set termguicolors
endif

colorscheme OceanicNext
```

Also installed vim 8 to test but no luck either 😕

**Comment by mhartington** [comment]
Using [this minimal gist](https://gist.github.com/mhartington/c331ecd81bedb5f88f5d97245e20d371), I have not been able to replicate.

<img width="445" alt="screen shot 2016-11-28 at 9 34 19 am" src="https://cloud.githubusercontent.com/assets/2835826/20672098/0ba60a62-b54e-11e6-8215-95e5ac6c3bd0.png">
 
Using vim 8

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 20 2016 19:04:13)
MacOS X (unix) version
Included patches: 1-94
```

**Comment by shelldandy** [comment]
Can it be because I'm using Vundle instead of Plug?

It almost looks like the previous oceanic next theme (the one im getting)

My current vimrc is this but i don't think I'm using any plugin that could mess with the colors

https://github.com/mike3run/dotfiles/blob/master/.vimrc

**Comment by sittim** [comment]
In my case for VIM8 and NeoVim  `colorscheme OceanicNext` did not work,  the following worked

```viml
let g:colors_name="OceanicNext"
let g:airline_theme='oceanicnext'
```

I do wonder why?

**Comment by mhartington** [comment]
That part should be fixed, in the last commit

https://github.com/mhartington/oceanic-next/commit/1b5d0b2e1569d1e2cde8ecc923ade90305228384#diff-e8a060cc160b2d21d9797efdd57a8fb7L10

**Comment by shelldandy** [comment]
![captura de pantalla 2016-11-28 a la s 10 55 17](https://cloud.githubusercontent.com/assets/7088511/20677620/31bfe654-b559-11e6-8951-4d971c9a50da.png)


Still not working well at least now the background is not gray... but now i don't have any colors :/

**Comment by sittim** [comment]
Just updated it, now In VIM8, now it does not work at all, in NeoVim, you have to re-source the rc file after opening for it to work.

**Comment by mhartington** [comment]
@mike3run you should not need the `let g:colors_name` bit, that is already fixed. That is not the issue.
Not sure on the vundle part, try vim-plug, as it is much easier and more modern. 

@sittim please provide a minimal vimrc to test against. 


Need to do work today, so I'll have to look tonight or in the next day, but PRs are always welcomed if you can fix it.

**Comment by shelldandy** [comment]
@mhartington i managed to somewhat fix it, so its funky inside tmux i already managed to enable everything however i see some blue backgrounds in every line of text

Is there a setting to take care of this?

![captura de pantalla 2016-11-28 a la s 11 13 31](https://cloud.githubusercontent.com/assets/7088511/20678364/06967850-b55c-11e6-9460-9d194e344086.png)

**Comment by mhartington** [comment]
That is not fixing things.... That is still broken

**Comment by sittim** [comment]
@mike3run, are you saying that it looks good outside of tmux and looks bad inside of tmux?  If that is the case, take  a look at:

https://github.com/icymind/NeoSolarized#truecolor-test

run the test in tmux, and follow the section **Tmux** to make it work inside the tmux...

**Comment by sittim** [comment]
Min .vimrc

```viml
call plug#begin('~/.vim/plugged')
Plug 'mhartington/oceanic-next'
call plug#end()

filetype plugin indent on " required

set termguicolors
set shell=bash

set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum

" ----- OceanicNext
"let g:colors_name="OceanicNext"
colorscheme OceanicNext
set background=dark
```

**Comment by mhartington** [comment]
@sittim these two lines break everything for me

```
set t_8f=�[38;2;%lu;%lu;%lum
set t_8b=�[48;2;%lu;%lu;%lum
```

what OS/terminal are you using?

@mike3run can you share your dot files. I'm not able to replicate. 
If you're trying to use a termguicolors, you'll need to enable them in tmux too.

```
set -g default-terminal "xterm-256color-italic"
set-option -ga terminal-overrides ',xterm-256color-italic:Tc'
```

http://homeonrails.com/2016/05/truecolor-in-gnome-terminal-tmux-and-neovim/

**Comment by sittim** [comment]
@mhartington, it works the same way in `gnome terminal` and in `st`, actually you do not need these two lines unless you use tmux, so just comment them out.  I am using Ubuntu 16.04, which uses gnome terminal v 3.18.3

**Comment by shelldandy** [comment]
okay i've installed neovim and it kind of works inside on tmux

![captura de pantalla 2016-11-28 a la s 19 22 20](https://cloud.githubusercontent.com/assets/7088511/20692835/1a30a4aa-b5a0-11e6-9b09-1b47a311e86d.png)

This is with set background=dark with this the background and colors look okay-ish (still not exactly like the screenshots on JS for example)

![captura de pantalla 2016-11-28 a la s 19 25 01](https://cloud.githubusercontent.com/assets/7088511/20692885/62ab3c54-b5a0-11e6-9984-925228c03f34.png)


If I remove that attribute i get italic comments but the colors become poopy:

![captura de pantalla 2016-11-28 a la s 19 21 46](https://cloud.githubusercontent.com/assets/7088511/20692875/5088708c-b5a0-11e6-9793-cda7a02c36be.png)

**Comment by mhartington** [comment]
ok, so I've updated the readme, as I just removed italics for a bit.

@mike3run the `set background=dark` should not be there, since it's already taken care of by the theme. As the readme states: 

```viml
" For Neovim 0.1.3 and 0.1.4
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

" Or if you have Neovim >= 0.1.5
if (has("termguicolors"))
 set termguicolors
endif

" Theme
syntax enable
colorscheme OceanicNext
```

There is no need to call it.

**Comment by sittim** [comment]
Awesome, not setting the background works for me for both VIM8 and NeoVim, but I will wait for the ability turn off italics.

**Comment by mhartington** [comment]
@sittim italics have been removed since yesterday. Please pull the latest commits

**Comment by olalonde** [comment]
I had the same issues as @mike3run but ended fixing most of it by enabling true color support in tmux. Still have a color that is a bit off in tmux strangely and opened a new issue: https://github.com/mhartington/oceanic-next/issues/40
